main: cn.wode490390.nukkit.cmdblock.CommandBlockPlugin
name: "SuperCommandBlock"
description: "SuperCommandBlock plugin for Nukkit"
authors: ["daoge cmd","wode"]
version: "${pom.version}"
api: ["1.0.1"]
load: STARTUP
