main: cn.wode490390.nukkit.cmdblock.CommandBlockPlugin
name: "SuperCommandBlock"
description: "SuperCommandBlock plugin for Nukkit"
author: "daoge cmd"
version: "${pom.version}"
api: ["1.0.0"]
load: STARTUP
